### ISSUE TITLE
Cannot download data

### ISSUE THREAD

**Issue by vahidAK** [jakelever/cancermine#1]
Hi @jakelever ,

I am trying to download different types of genes based on cancer type for medulloblastoma from http://bionlp.bcgsc.ca/cancermine/. But when I want to download the table it says "download failed".
Do you know what is wrong?

Thanks,
Vahid.

**Comment by jakelever** [comment]
Hey, thank you for raising this. It was a really quick fix and should now be working. Let me know if you find any other bugs. Thanks!

**Comment by vahidAK** [comment]
Thanks @jakelever , it is now working just fine
