### ISSUE TITLE
Minor issue - TTN as oncogene

### ISSUE THREAD

**Issue by sigven** [jakelever/cancermine#3]
Hi @jakelever,

Just discovered what I believe to be an artefact from the latest release, indicating quite some support for TTN as an oncogene. Having looked at the sentences in the supporting citations (using http://bionlp.bcgsc.ca/cancermine/), it seems that TTN is mistakenly (?) tagged in the context of a non-coding RNA with a name that includes TTN (TTN-AS1). Given that TTN is one of the largest protein-coding genes, mutations in this gene are very frequent in human tumors (purely by chance due to its large size), but quite sure this is not an oncogene.

Just thought it might be relevant for check/improvements of your text mining pipeline.

kind regards,
Sigve

**Comment by jakelever** [comment]
Nice catch. I'm adding it to the exclusion list for filtering out and will check it's fixed in the next version. Thanks!
