### ISSUE TITLE
Minor issue - antisense (AS1) occurrences

### ISSUE THREAD

**Issue by sigven** [jakelever/cancermine#5]
Hi Jake,

Lately, I discovered a minor issue with some of the hits. As it happens, a lot of protein-coding genes also have an antisense transcript, and it seems as if these occurrences in the literature are catched along with the primary (protein-coding) genes. Basically, you will see occurrences of `<gene_symbol>-AS1`  in addition to `<gene_symbol>`, which are currently both normalized to `gene_symbol`, but ideally I think they should probably be considered separate entities? I have set up a simple post-filter scheme to catch them, but if you are not aware I thought it might be of interest.

kind regards,
Sigve

**Comment by jakelever** [comment]
Hey @sigven , I came across this problem in another project and hadn't realised it was an issue in CancerMine. Thanks for pointing it out. I'll take a look and probably implement a similar filter in the pipeline. Thanks!

**Comment by jakelever** [comment]
That's the filter added for the latest update. Thanks for pointing this out
