### ISSUE TITLE
Error in accessing the web portal

### ISSUE THREAD

**Issue by songsong0425** [jakelever/cancermine#6]
Hi, thank you for your effort in constructing a database for the cancer driver genes.
I have a question about the web portal.
When I tried to use the database from https://bionlp.bcgsc.ca/cancermine/ , I couldn't access to the site with the error.

> The following error was encountered while trying to retrieve the URL: https://bionlp.bcgsc.ca/cancermine/
>
> This request could not be forwarded to the origin server or to any parent caches.
> 
> Some possible problems are:
> 
> An Internet connection needed to access this domains origin servers may be down.
> All configured parent caches may be currently unreachable.
> The administrator may not allow this cache to make direct connections to origin servers.
>Your cache administrator is root.

Can you check it?

**Comment by jakelever** [comment]
Hi, thanks for raising this. Google/Chrome seem to be redirecting to the
HTTPS address when the server is running on HTTP. You should be able to
access it at http://bionlp.bcgsc.ca/cancermine/ through other browsers.
I'll try to resolve this with a proper solution in the future

**Comment by songsong0425** [comment]
Thank you for your kind and prompt reply!
It works great for me.
